name: build_emails
on:
  push:
    # paths:
    #   - "src/Services/Emails/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: ams0/acr-task-github-action@v1
        with:
          service_principal: ${{ secrets.REGISTRY_USERNAME }}
          service_principal_password: ${{ secrets.REGISTRY_PASSWORD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.REGISTRY_REPOSITORY }}
          folder: ./src/Services/Emails/Emails.api
          dockerfile: Dockerfile